[project]
name = "dark-chess"
version = "0.1.0"
description = "Dark chess environment"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "yunik1004", email = "inkyuhak@gmail.com" },
]
dependencies = [
    "cairosvg>=2.7.1",
    "chess>=1.11.1",
    "imageio[ffmpeg]>=2.35.1",
    "open-spiel>=1.4",
    "pettingzoo>=1.24.3",
    "shimmy[open-spiel]>=2.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]
